### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by tdmalone** [codrops/AnimatedSVGIcons#1]
In `js/svgicons.js`, the header specifies:

```
 * Licensed under the MIT license.
 * http://www.opensource.org/licenses/mit-license.php
```

The MIT license permits to "...deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies".

However the README links to http://tympanus.net/codrops/licensing/, which states "you are not allowed to take our work “as-is” and sell it, redistribute or re-publish it..."

Could you please clarify which license applies to this repo?

**Comment by crnacura** [comment]
The JS file is licensed und MIT. However, it's not allowed to take the complete work **as-is**, i.e. the demo, and sell it, redistribute or re-publish it. Let me know if this clarifies it.

**Comment by tdmalone** [comment]
Great, that makes sense. Thanks very much!
